covid_starterpack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('covid_kit/', include('covid_kit.urls', namespace='covid_kit')),
    path('daftar-rs/', include(('list_rs.urls', 'list_rs'), namespace='list_rs')),
    path('daftarkasus/', include('list_kasus.urls',namespace ='listkasus')),
    path('berita/', include('berita.urls')),
    path('contact/', include('contact.urls')),
    path('faq/', include('faq.urls', namespace='faq')),
]

faq/urls.py
from django.urls import path, include

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq, name='faq'),
    path('list-pertanyaan/', views.list_pertanyaan, name='list-pertanyaan'),
    path('jawab/P<int:id_pertanyaan>/', views.jawab, name='jawab'),
    path('list-FAQ/', views.list_faq, name='list-faq'),
    path('detail/P<int:id_pertanyaan>/', views.detail, name='detail'),
]

list_rs/urls.py
from django.urls import path

from . import views

app_name = 'list_rs'

urlpatterns = [
    path('', views.savers, name='savers'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('hapus/<str:id>', views.hapus, name='hapus'),
    path('ubah/<str:id>', views.ubah, name='ubah'),
    path('tes-covid/', views.tescovid, name='tescovid'),
    path('tes-covid/tiket', views.savependaftar),
]

list_rs/models.py
from django.db import models

class RumahSakit(models.Model):
    nama = models.CharField(max_length=200)
    provinsi = models.CharField(max_length=200)
    kabkota = models.CharField(max_length=200)
    alamat = models.TextField(blank=False, null=False)
    telepon = models.CharField(max_length=200)

    def __str__(self):
        return self.nama

class PendaftarRapid(models.Model):
    nama = models.CharField(max_length=200)
    no_id = models.CharField(max_length=200)
    telepon = models.CharField(max_length=200)
    alamat = models.TextField(blank=False, null=False)
    tempat = models.CharField(max_length=200)

class PendaftarSwab(models.Model):
    nama = models.CharField(max_length=200)
    no_id = models.CharField(max_length=200)
    telepon = models.CharField(max_length=200)
    alamat = models.TextField(blank=False, null=False)
    tempat = models.CharField(max_length=200)

list_rs/forms.py
from django import forms
from .models import RumahSakit, PendaftarRapid, PendaftarSwab

class Input_RS(forms.ModelForm):
    class Meta:
        model = RumahSakit
        fields = ['nama', 'provinsi', 'kabkota', 'alamat', 'telepon']
    
        labels = {
            'nama' : 'Nama Rumah Sakit:',
            'provinsi' : 'Provinsi:',
            'kabkota' : 'Kabupaten / Kota:',
            'alamat' : 'Alamat:',
            'telepon' : 'No. Telepon:',
        }
        input_attrs = {
            'type' : 'text',
            'class' : 'form-control'
        }
        widgets = {
            'nama' : forms.TextInput(attrs=input_attrs),
            'provinsi' : forms.TextInput(attrs=input_attrs),
            'kabkota' : forms.TextInput(attrs=input_attrs),
            'alamat' : forms.Textarea(attrs=input_attrs),
            'telepon' : forms.TextInput(attrs=input_attrs),
        }

class Input_Tes(forms.Form):
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'class' : 'form-control'
    }

    nama = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    no_id = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    telepon = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    alamat = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=input_attrs))
    tempat = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    
    TESCOVID = (
        ('1', 'Rapid Test'),
        ('2', 'Swab Test'),
    )
    tes = forms.ChoiceField(choices=TESCOVID, label='', required=True, widget=forms.Select(attrs=input_attrs))

list_rs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Input_RS, Input_Tes
from .models import RumahSakit, PendaftarRapid, PendaftarSwab
from django.contrib import messages

response = {}

def savers(request):
    form = Input_RS(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        form.save()
    rsrujukans = RumahSakit.objects.all()
    jumlahrs = RumahSakit.objects.count()
    response = {'input_rs' : Input_RS, 'rsrujukans':rsrujukans, 'jumlahrs':jumlahrs}
    return render(request, 'daftarrs.html', response)

def detail(request, id):
    rsrujukan = RumahSakit.objects.get(id=id)
    response = {'rsrujukan' : rsrujukan}
    return render(request, "detailrs.html", response)

def hapus(request, id):
    rsrujukan = RumahSakit.objects.get(id=id)
    rsrujukan.delete()
    messages.warning(request, (f"{rsrujukan} berhasil dihapus!"))
    return redirect('list_rs:savers')

def ubah(request, id):
    rsrujukan = RumahSakit.objects.get(id=id)
    if request.method == 'GET':
        form = Input_RS(instance=rsrujukan)
    if request.method == 'POST':
        form = Input_RS(request.POST, instance=rsrujukan)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect('/daftar-rs/')
    response = {'input_rs' : form, 'rsrujukan':rsrujukan}
    return render(request, 'ubahrs.html', response)
    
def tescovid(request):
    response = {'input_tes' : Input_Tes}
    return render(request, "tescovid.html", response)

def savependaftar(request):
    form = Input_Tes(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        if (request.POST['tes'] == '1'):
            pendaftar = PendaftarRapid.objects.create(nama=request.POST['nama'], 
                no_id=request.POST['no_id'], telepon=request.POST['telepon'],
                alamat=request.POST['alamat'], tempat=request.POST['tempat'])
        else:
            pendaftar = PendaftarSwab.objects.create(nama=request.POST['nama'], 
                no_id=request.POST['no_id'], telepon=request.POST['telepon'],
                alamat=request.POST['alamat'], tempat=request.POST['tempat'])
        response = {'id' : pendaftar.id}
        return render(request, "tikettes.html", response)
    else:
        return HttpResponseRedirect('/daftar-rs/tes-covid/')
        

list_rs/templates/daftarrs.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styleV.css' %}">
<title>Daftar RS Rujukan COVID-19</title>
{% endblock meta %}

{% block content %}
    <div class="container-fluid p-3 my-3 text-center">
        <h1>Daftar Rumah Sakit Rujukan</h1>
    </div>
    <div class="container-fluid header">
        <div class="row">
            <div class = "pic col-sm-12 col-md-6 pt-sm-4 pt-md-1">
                <img src= "{% static 'rs.png' %}" class="img-fluid mx-auto" style="width: 90%; height: auto;">
            </div>
            <div class="para col-sm-12 col-md-6 text-center pr-md-5 pb-md-3 px-4 pt-5">
                <p>Telah terdaftar sebanyak {% if rsrujukans %} {{ jumlahrs }} {% endif %}
                    {% if not rsrujukans %} 0 {% endif %}
                    rumah sakit rujukan yang siap menangani pasien COVID-19 pada website ini.
                <br><br>Tambahkan jumlah rumah sakit rujukan COVID-19 agar pandemi ini segera berakhir.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid p-4 my-2 pb-5 text-center">
        <div class="pt-sm-5 pt-4">
            <h2>Kapan <span>Perlu </span>Memeriksakan Kesehatan Ke Rumah Sakit
            untuk Dugaan <span>COVID-19</span>?</h2>
        </div>
        <div class="py-sm-4 py-3">
            <br>
            <img class="img-fluid" src= "{% static 'kapan.png' %}">
        </div><br>
        <a class="btn btn-danger btn-lg" href="{% url 'list_rs:tescovid' %}">Daftar Rapid Test/Swab Test</a>
    </div>
    <div class="container-fluid p-md-5 py-5" style="background-color: #4ECDC4;">
        <div class="p-md-5 pb-2 pt-1 text-center">
            <h2 style="color: #0E434B;">Daftarkan Rumah Sakit Rujukan Anda.</h2><br>
        </div>
        <div class="form">
            <div class="form-group">
                <form action="" method="POST">
                    {% csrf_token %}
                    {% for form in input_rs %}
                        {{ form.label }}
                        {{ form }} <br>
                    {% endfor %}
                    <div class="text-right">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <div class="container-fluid p-sm-5 px-3 py-4">
        <div class="p-md-5 p-2 pt-4 text-center">
            <h2>Daftar Rumah Sakit Rujukan</h2><br>
        </div>
        <table id="list" class="table table-hover">
            <tr>
            <th>Nama Rumah Sakit</th>
            <th></th>
            <th></th>
            </tr>
            {% if rsrujukans %}
            <tbody>
                {% for rsrujukan in rsrujukans %}
                    <tr>
                        <td><a href="{% url 'list_rs:detail' id=rsrujukan.id %}" class="detail">{{ rsrujukan }}</a></td>
                        <td class="center"><a class="btn btn-warning" href="{% url 'list_rs:ubah' id=rsrujukan.id %}">Ubah</a></td>
                        <td class="center">
                            <a href="{% url 'list_rs:hapus' id=rsrujukan.id %}">
                            <button type="button" class="btn btn-danger">Hapus</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            {% endif %}
            {% if not rsrujukans %}
            <tbody>
                <tr class="text-center">
                <td colspan="3"><p>Belum ada rumah sakit rujukan yang terdaftar.</p></td>
                </tr>
            </tbody>
            {% endif %}
        </table>
        <br><br>
        {% if messages %}
        {% for message in messages %}
        {% if forloop.last %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
                {{ message }}
                <button type="button" class="btn btn-danger" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    </div>
    
    
    
{% endblock content%}

list_rs/templates/detailrs.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styleV.css' %}">
<title>Detail {{ rsrujukan }}</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid p-3 my-3 text-white text-md-left text-center">
    <h1 class="pl-md-5">Detail {{ rsrujukan }}</h1>
</div>

<div class="container-fluid p-3 px-5 text-left" style="background-color: #4ECDC4;">
    <div class="row mx-md-5 mx-3 px-md-4">
        <div class="col-sm-12 px-md-5"></div>
            <br>
            <p><b><b>Nama Rumah Sakit:</b></b><br>{{ rsrujukan.nama }}<br>
            <br><b><b>Provinsi:</b></b><br>{{ rsrujukan.provinsi }}<br>
            <br><b><b>Kabupaten / Kota:</b></b><br>{{ rsrujukan.kabkota }}<br>
            <br><b><b>Alamat:</b></b><br>{{ rsrujukan.alamat }}<br>
            <br><b><b>No. Telepon:</b></b><br>{{ rsrujukan.telepon }}<br>
            <p></p>
        </div>
    </div>
</div>
<div class="container-fluid px-md-5 pb-2 text-white text-md-right text-center">
    <br>
    <p><a class="back" href="{% url 'list_rs:savers' %}">Kembali daftar rumah sakit rujukan</a><br></p>
</div>
{% endblock content %}

list_rs/templates/tescovid.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styleV.css' %}">
<title>Daftar Tes COVID-19</title>
<style>
    #desktop {display: block;}
    #mobile {display: none;}
    @media screen and (max-width: 768px) {
        #desktop {display: none;}
        #mobile {display: block;}
    }
</style>
{% endblock meta %}

{% block content %}
    <div class="container-fluid p-3 my-3 text-center">
        <h1>Daftar Rapid Test / Swab Test</h1>
    </div>
    <div class= "container-fluid px-md-5 px-2 py-md-2" style ="background-color:#FFE66D;">
        <h2 class="text-md-left text-center pl-md-5" style="margin-bottom: -1px; color:#1A535C">Rapid Test</h2>
    </div>
    <div class="container-fluid desc">
        <div class="row">
            <div id="desktop" class="para col-sm-12 col-md-6 text-justify pr-md-5 pb-md-3 px-4 pt-5">
                <ul>
                    <li>- Menggunakan sampel darah yang diambil untuk diuji</li>
                    <li>- Jika jumlah antibodi IgG dan IgM dalam darah bertambah maka terjadi infeksi virus</li>
                    <li>- Hanya membutuhkan waktu 10-15 menit hingga hasil keluar</li>
                    <li>- Hanya untuk screening awal</li>
                </ul>
            </div>
            <div class = "pic col-sm-12 col-md-6 pt-sm-4 pt-md-1">
                <img src= "{% static 'rapid.png' %}" class="img-fluid mx-auto" style="width: 90%; height: auto;">
            </div>
            <div id="mobile" class="para col-sm-12 col-md-6 text-justify pr-md-5 pb-md-3 px-4 pt-5">
                <ul>
                    <li>- Menggunakan sampel darah yang diambil untuk diuji</li>
                    <li>- Jika jumlah antibodi IgG dan IgM dalam darah bertambah maka terjadi infeksi virus</li>
                    <li>- Hanya membutuhkan waktu 10-15 menit hingga hasil keluar</li>
                    <li>- Hanya untuk screening awal</li>
                </ul>
            </div>
        </div>
    </div>
    <div class= "container-fluid px-md-5 px-2 py-md-2" style ="background-color: #FFE66D;">
        <h2 class="text-md-right text-center pr-md-5" style="margin-bottom: -1px; color:#1A535C">Swab Test</h2>
    </div>
    <div class="container-fluid desc">
        <div class="row">
            <div class = "pic col-sm-12 col-md-6 pt-sm-4 pt-md-1">
                <img src= "{% static 'swab.png' %}" class="img-fluid mx-auto" style="width: 90%; height: auto;">
            </div>
            <div class="para col-sm-12 col-md-6 text-justify pr-md-5 pb-md-3 px-4 pt-5">
                <ul>
                    <li>- Menggunakan sampel lendir dalam lubang hidung dan tenggorokan</li>
                    <li>- Menggunakan metode PCR (Polymerase Chain Reaction)</li>
                    <li>- Membutuhkan waktu beberapa jam/hari hingga hasil keluar</li>
                    <li>- Metode paling akurat dalam mendeteksi virus SARS-COV2</li>
                </ul>
            </div>
        </div>
    </div>
    <br>
    <div class="container-fluid p-md-5 py-5">
        <div class="form">
            <div class="form-group">
                <form action="tiket" method="POST">
                    {% csrf_token %}
                    Nama Lengkap: {{ input_tes.nama }}<br>
                    No. KTP: {{ input_tes.no_id }}<br>
                    No. Telepon: {{ input_tes.telepon }}<br>
                    Alamat: {{ input_tes.alamat }}<br>
                    Rumah Sakit / Klinik: {{ input_tes.tempat }}<br>
                    Rapid / Swab: {{ input_tes.tes }}<br><br>
                    <div class="text-right">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container-fluid px-md-5 pb-2 text-white text-md-right text-center">
        <p><a class="back" href="{% url 'list_rs:savers' %}">Kembali daftar rumah sakit rujukan</a><br></p>
    </div>
{% endblock content %}

list_rs/templates/tikettes.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styleV.css' %}">
<title>Tiket Antrian No. {{ id }}</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid text-center" style="padding: 50px 20px;">
    <h2>Nomor Antrian Anda:
        <br>{{ id }}
        <br>Kode Tiket:
        <br>{{ id }}
    </h2>
    <br>
    <div class="container buttons">
        <div class="row">
            <div class="col-sm-6 col-12 p-3">
                <a href="#" class="btn btn-warning btn-lg">Download Tiket</a>
            </div>
            <div class="col-sm-6 col-12 p-3">
                <a href="{% url 'list_rs:savers' %}" class="btn btn-warning btn-lg" style="width: 194px;">Kembali</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

list_rs/templates/ubahrs.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styleV.css' %}">
<title>Ubah Data {{ rsrujukan }}</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid p-md-5 py-5" style="background-color: #4ECDC4;">
    <div class="p-md-5 pb-2 text-center">
        <h2 style="color: #0E434B;">Ubah Data {{ rsrujukan }}.</h2><br>
    </div>
    <div class="form">
        <div class="form-group">
            <form action="" method="POST">
                {% csrf_token %}
                {% for form in input_rs %}
                    {{ form.label }}
                    {{ form }} 
                    <br>
                {% endfor %}
                <div class="text-right">
                    <input type="submit" value="Submit" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
<div class="container-fluid px-md-5 pb-2 text-white text-md-right text-center">
    <br>
    <p><a class="back" href="{% url 'list_rs:savers' %}">Kembali daftar rumah sakit rujukan</a></p>
</div>
{% endblock content %}