covid_starterpack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('covid_kit/', include('covid_kit.urls', namespace='covid_kit')),
    path('daftar-rs/', include(('list_rs.urls', 'list_rs'), namespace='list_rs')),
    path('daftarkasus/', include('list_kasus.urls',namespace ='listkasus')),
    path('berita/', include('berita.urls')),
    path('contact/', include('contact.urls')),
    path('faq/', include('faq.urls', namespace='faq')),
]

faq/urls.py
from django.urls import path, include

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq, name='faq'),
    path('list-pertanyaan/', views.list_pertanyaan, name='list-pertanyaan'),
    path('jawab/P<int:id_pertanyaan>/', views.jawab, name='jawab'),
    path('list-FAQ/', views.list_faq, name='list-faq'),
    path('detail/P<int:id_pertanyaan>/', views.detail, name='detail'),
]

faq/models.py
from django.db import models

# Create your models here.

class ModelPertanyaan(models.Model):
    pertanyaan = models.CharField(max_length=1000)

    def __str__(self):
        return self.pertanyaan


class ModelJawaban(models.Model):
    pengisi = models.CharField(max_length=100)
    jawaban = models.TextField(blank=False)
    isi_pertanyaan = models.OneToOneField(ModelPertanyaan, on_delete=models.CASCADE, primary_key=True)

faq/forms.py
from django import forms

class FormPertanyaan(forms.Form):
    pertanyaan = forms.CharField(
        widget = forms.TextInput(attrs={'placeholder':'Ask your question here...', 'style':'width:30%; border-radius:5px'})
    )

class FormJawaban(forms.Form):
    pengisi = forms.CharField(
        label = 'Dijawab oleh:',
        widget = forms.TextInput(attrs={'style':'width:100%'})
    )
    jawaban = forms.CharField(
        widget = forms.Textarea(attrs={'style':'width:100%'})
    )

faq/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import FormPertanyaan, FormJawaban
from .models import ModelPertanyaan, ModelJawaban

def faq(request):
    form_pertanyaan = FormPertanyaan()
    if request.method == 'POST':
        input_form_pertanyaan = FormPertanyaan(request.POST)
        if input_form_pertanyaan.is_valid():
            ModelPertanyaan.objects.create(
                pertanyaan = input_form_pertanyaan.cleaned_data.get('pertanyaan')
            )
        return HttpResponseRedirect('/faq/list-pertanyaan/')
    context = {
        'form_pertanyaan':form_pertanyaan
    }
    return render(request, 'faq/faq.html', context)

def list_pertanyaan(request):
    pertanyaans = ModelPertanyaan.objects.all()
    context = {
        'pertanyaans':pertanyaans
    }
    return render(request, 'faq/list-pertanyaan.html', context)

def jawab(request, id_pertanyaan):
    form_jawaban = FormJawaban()
    if request.method == 'POST':
        input_form_jawaban = FormJawaban(request.POST)
        if input_form_jawaban.is_valid():
            data = input_form_jawaban.cleaned_data
            objek_jawaban = ModelJawaban()
            objek_jawaban.pengisi = data['pengisi']
            objek_jawaban.jawaban = data['jawaban']
            objek_jawaban.isi_pertanyaan = ModelPertanyaan.objects.get(id=id_pertanyaan)
            objek_jawaban.save()
            return HttpResponseRedirect('/faq/list-FAQ/')
    context = {
        'form_jawaban':form_jawaban
    }
    return render(request, 'faq/jawab.html', context)

def list_faq(request):
    faqs = ModelPertanyaan.objects.all()
    context = {
        'faqs':faqs
    }
    return render(request, 'faq/list-faq.html', context)

def detail(request, id_pertanyaan):
    pertanyaan = ModelPertanyaan.objects.filter(id=id_pertanyaan).get(id=id_pertanyaan)
    jawabans = ModelJawaban.objects.all()
    context = {
        'pertanyaan':pertanyaan,
        'jawabans':jawabans
    }
    return render(request, 'faq/detail.html', context)

faq/templates/faq/detail.html
{% extends 'base.html' %} 
{% load static %}
{% block meta %}
<link href="{% static 'cssfaq.css' %}" rel="stylesheet" type="text/css">
<style>
    .navbar{
        color: black;
        padding-right: 0%;
    }
    .navbar a{
        text-decoration: none;
        color: black;
        word-wrap: break-word;
        padding-left: 0%;
        padding-right: 0%;
    }
    .navbar div.collapse.navbar-collapse#navbarNavAltMarkup div.navbar-nav.ml-auto{
        padding-right: 0%;
    }
    footer{
        color: black;
        font-family: 'Poppins', sans-serif;
    }
</style>
{% endblock meta %}

{% block content %}
<body>
    <div class="title">
        <p class="p-title">Frequently Asked Questions</p>
    </div>
    <div class="col text-center" style="margin-top: 100px;">
        <table style="width: 100%; text-align: justify;">
            {% for jawaban in jawabans %}
            {% if jawaban.isi_pertanyaan == pertanyaan %}
            <tr>
                <th class="col-md-auto">Dijawab Oleh:</th>
                <td class="col-md-auto">{{jawaban.pengisi}}</td>
            </tr>
            <tr>
                <th class="col-md-auto">Pertanyaan:</th>
                <td class="col-md-auto">{{jawaban.isi_pertanyaan}}</td>
            </tr>
            <tr>
                <th class="col-md-auto">Jawaban:</th>
                <td class="col-md-auto">{{jawaban.jawaban}}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </table>
    </div>
    <br>
    <div class="row mb-3 justify-content-center mt-3">
        <div class="col text-center">
            <a href="{% url 'faq:list-faq' %}" class="btn" style="background-color: #FFE66D;">Kembali</a>
        </div>
    </div>        
{% endblock content %}

faq/templates/faq/faq.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<link href="{% static 'cssfaq.css' %}" rel="stylesheet" type="text/css">
<style>
    .navbar{
        color: black;
        padding-right: 0%;
    }
    .navbar a{
        text-decoration: none;
        color: black;
        word-wrap: break-word;
        padding-left: 0%;
        padding-right: 0%;
    }
    .navbar div.collapse.navbar-collapse#navbarNavAltMarkup div.navbar-nav.ml-auto{
        padding-right: 0%;
    }
    footer{
        color: black;
        font-family: 'Poppins', sans-serif;
    }
</style>
{% endblock meta %}

    {% block content %}
    <div class="title">
        <p class="p-title">Frequently Asked Questions</p>
    </div>
    <div class="d-flex justify-content-around mt-5">
        <div>
            <a type="button" class="btn" style="background-color: #FFE66D;" href="{% url 'faq:faq' %}#tentang-covid19">Tentang COVID-19</a>
        </div>
        <div>
            <a type="button" class="btn" style="background-color: #FFE66D;" href="{% url 'faq:faq' %}#cara-pencegahan">Cara Pencegahan</a>
        </div>
        <div>
            <a type="button" class="btn" style="background-color: #FFE66D;" href="{% url 'faq:faq' %}#penanganan-dan-pengobatan">Penanganan dan Pengobatan</a>
        </div>
    </div>
    <div id="tentang-covid19" class="mt-5">
        <p><b>Tentang COVID-19</b></p>
        <p class="border-bottom">Apa itu COVID-19?<span data-toggle="collapse" data-target="#tentang-satu" class="class-collapse">▼</span></p> 
        <div id="tentang-satu" class="collapse">
            COVID-19 adalah penyakit menular yang disebabkan oleh virus corona SARS-CoV-2. 
            Dengan kata lain, SARS-CoV-2 adalah nama virusnya, sementara COVID-19 adalah nama penyakitnya.
            Ini seperti HIV yang adalah nama virus dari penyakit AIDS.
        </div>
        <p class="border-bottom mt-3">Apa itu virus Corona?<span data-toggle="collapse" data-target="#tentang-dua" class="class-collapse">▼</span></p>
        <div id="tentang-dua" class="collapse">
            Virus Corona adalah sebutan untuk jenis virus yang dapat menyebabkan penyakit pada hewan dan manusia. Disebut corona karena bentuknya yang seperti mahkota. 
            Beberapa contoh penyakit pada manusia yang disebabkan oleh virus corona antara lain MERS dan SARS. 
            Virus corona terbaru yang ditemukan yang ditemukan di Wuhan, Tiongkok, pada bulan Desember 2019 diberi nama SARS Coronavirus 2, disingkat SARS-CoV-2, dan menyebabkan penyakit Coronavirus Disease 2019, disingkat COVID-19.
        </div>
        <p class="border-bottom mt-3">Bagaimana cara COVID-19 menular?<span data-toggle="collapse" data-target="#tentang-tiga" class="class-collapse">▼</span></p>
        <div id="tentang-tiga" class="collapse">
            Penularan terjadi melalui droplet, yaitu butir-butir tetesan cairan, dari hidung atau mulut yang menyebar saat pembawa virus COVID-19 batuk atau bersin.
            Tetesan cairan tersebut akan menempel pada benda atau permukaan di sekitarnya. Kemudian masuk ke mulut, hidung, atau mata. 
            Dapat juga karena menyentuh permukaan bekas terkena butir cairannya dengan tangan lalu tangan mengusap mulut, hidung, atau mata. 
            Inilah alasan pentingnya sering-sering cuci tangan dan jangan menyentuh muka dengan tangan.
            Orang sehat dapat tertular saat tangan mereka menyentuh permukaan yang terkena tetesan tersebut dan kemudian tanpa sadar menyentuh mata, mulut, ataupun hidung. 
            Virus juga bisa masuk saat orang sehat secara tidak sengaja menghirup tetesan cairan saat si pembawa virus batuk atau bersin.
        </div>
    </div>
    <div id="cara-pencegahan" class="mt-5">
        <p><b>Cara Pencegahan</b></p>
        <p class="border-bottom">Bagaimana cara menjaga diri agar terhindar dari COVID-19?<span data-toggle="collapse" data-target="#cegah-satu" class="class-collapse">▼</span></p> 
        <div id="cegah-satu" class="collapse">
            Untuk mencegah diri dari COVID-19, WHO dan Pemerintah menyarankan kepada masyarakat untuk:
            <ul>
                <li>Rajin membersihkan tangan dengan sabun dan air mengalir atau dengan hand sanitizer</li>
                <li>Menggunakan masker ketika berpergian</li>
                <li>Tidak menyentuh muka bagian mata, hidung, dan mulut dengan tangan yang belum dibersihkan</li>
                <li>Menutup hidung dan mulut menggunakan siku bagian dalam saat batuk atau bersin</li>
                <li>Menjaga jarak minimal satu meter dengan orang lain</li>
                <li>Tetap berada di rumah jika tidak ada kepentingan</li>
            </ul>
        </div>
        <p class="border-bottom mt-3">Apa dan Bagaimana Physical Distancing?<span data-toggle="collapse" data-target="#cegah-dua" class="class-collapse">▼</span></p>
        <div id="cegah-dua" class="collapse">
            Physical distancing adalah upaya yang dilakukan untuk mencegah penyebaran virus corona di masyarakat. 
            Secara sederhana Physical Distancing adalah menjaga jarak lebih dari 1 meter dengan siapapun. Dengan kata lain: Tidak Berdekatan dan Tidak Berkumpul.
            Dengan menerapkan Physical Distancing penyebaran virus dapat dicegah. Ingat, virus tidak bergerak sendiri tapi oranglah yang membawanya ke mana-mana.
        </div>
        <p class="border-bottom mt-3">Apa saja protokol kesehatan yang harus diterapkan saat berpergian keluar rumah?<span data-toggle="collapse" data-target="#cegah-tiga" class="class-collapse">▼</span></p>
        <div id="cegah-tiga" class="collapse">
            Protokol kesehatan yang harus dilaksanakan saat berpergian ke luar rumah adalah:
            <ul>
                <li>Gunakan pakaian lengan panjang</li>
                <li>Bawa hand-sanitizer dengan kandungan alkohol minimal 60%</li>
                <li>Gunakan masker</li>
                <li>Hindari keramaian</li>
                <li>Jaga jarak minimal satu meter</li>
                <li>Gunakan transaksi nontunai</li>
                <li>Bersihkan tangan menggunakan sabun dan air mengalir atau hand sanitizer setelah menyentuh benda atau permukaan apa pun</li>
            </ul>
        </div>
    </div>
    <div id="penanganan-dan-pengobatan" class="mt-5">
        <p><b>Penanganan dan Pengobatan</b></p>
        <p class="border-bottom">Bagaimana saya dapat dinyatakan positif atau negatif COVID-19?<span data-toggle="collapse" data-target="#penanganan-satu" class="class-collapse">▼</span></p> 
        <div id="penanganan-satu" class="collapse">
            Untuk mengetahui apakah seseorang positif atau negatif COVID-19, perlu diadakan tes yang disebut Swab Test/PCR Test.
            Tes dilakukan dengan cara mengambil sampel spesimen menggunakan alat berbentuk batang cotton bud dengan ukuran yang lebih panjang melalui hidung dan mulut.
            Kemudian, sampel akan dikirim ke laboratorium untuk dites PCR. Hasil dari tes inilah yang akan menyatakan seseorang positif atau negatif COVID-19.
        </div>
        <p class="border-bottom mt-3">Apakah vaksin COVID-19 sudah tersedia? Kapan bisa digunakan?<span data-toggle="collapse" data-target="#penanganan-dua" class="class-collapse">▼</span></p>
        <div id="penanganan-dua" class="collapse">
            Saat ini belum ada pengobatan khusus yang efektif untuk infeksi virus corona baru. 
            Vaksin mungkin baru bisa tersedia pada tahun 2021.
            Sumber: covid19.go.id
        </div>
        <p class="border-bottom mt-3">Adakah obat khusus untuk menangani COVID-19?<span data-toggle="collapse" data-target="#penanganan-tiga" class="class-collapse">▼</span></p>
        <div id="penanganan-tiga" class="collapse">
            Sampai saat ini, belum ada obat khusus yang disarankan untuk mencegah atau mengobati penyakit yang disebabkan virus corona baru. 
            Mereka yang terinfeksi virus harus menerima perawatan yang tepat untuk meredakan dan mengobati gejala, dan mereka yang sakit serius harus dibawa ke rumah sakit.
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <p class="btn"><a href="{% url 'faq:list-faq' %}"><u>Lihat FAQ lain</u></a></li>
        <p class="btn"><a href="{% url 'faq:list-pertanyaan' %}"><u>Jawab pertanyaan lain</u></a></li>
    </div>
    <div class="mt-5 mb-5">
        <form method="POST" class="d-flex justify-content-center">
            {% csrf_token %}
            {{form_pertanyaan.pertanyaan}}
            <button type="submit" class="btn ml-3" style="float: right; background-color: #FFE66D;">Send</button>
        </form>
    </div>
    {% endblock content %}

faq/templates/faq/jawab.html
{% extends 'base.html' %} 
{% load static %}
{% block meta %}
<link href="{% static 'cssfaq.css' %}" rel="stylesheet" type="text/css">
<style>
    .navbar{
        color: black;
        padding-right: 0%;
    }
    .navbar a{
        text-decoration: none;
        color: black;
        word-wrap: break-word;
        padding-left: 0%;
        padding-right: 0%;
    }
    .navbar div.collapse.navbar-collapse#navbarNavAltMarkup div.navbar-nav.ml-auto{
        padding-right: 0%;
    }
    footer{
        color: black;
        font-family: 'Poppins', sans-serif;
    }
</style>
{% endblock meta %}

{% block content %}
    <div class="title">
        <p class="p-title">Frequently Asked Questions</p>
    </div>
    <div class="mb-5">
        <div>
            <div class="fr-form">
                <form method="POST" style="width: 100%;">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="p-jawab d-flex justify-content-start">
                            {{form_jawaban.pengisi.label_tag}}
                        </div>
                        {{form_jawaban.pengisi}}
                    </div>
                    <div class="form-group">
                        <div class="p-jawab d-flex justify-content-start">
                            {{form_jawaban.jawaban.label_tag}}
                        </div>
                        {{form_jawaban.jawaban}}
                    </div>
                    <div class="d-flex justify-content-end mb-3">
                        <button type="submit" class="btn" style="background-color: #FFE66D;">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

faq/templates/faq/list-faq.html
{% extends 'base.html' %} 
{% load static %}
{% block meta %}
<link href="{% static 'cssfaq.css' %}" rel="stylesheet" type="text/css">
<style>
    .navbar{
        color: black;
        padding-right: 0%;
    }
    .navbar a{
        text-decoration: none;
        color: black;
        word-wrap: break-word;
        padding-left: 0%;
        padding-right: 0%;
    }
    .navbar div.collapse.navbar-collapse#navbarNavAltMarkup div.navbar-nav.ml-auto{
        padding-right: 0%;
    }
    footer{
        color: black;
        font-family: 'Poppins', sans-serif;
    }
</style>
{% endblock meta %}

{% block content %}
    <div class="title">
        <p class="p-title">Frequently Asked Questions</p>
    </div>
    <div style="margin-top: 80px;">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">List Pertanyaan</th>
            </tr>
            </thead>
            <tbody>
                {% for faq in faqs %}
                    <tr>
                        <td><a class="p-td" href="{% url 'faq:detail' faq.id %}"><u>{{faq.pertanyaan}}</u></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row mb-3 justify-content-center">
        <div class="col text-center">
            <a href="{% url 'faq:faq' %}" class="btn" style="background-color: #FFE66D;">Kembali ke Halaman FAQ</a>
        </div>
    </div>
{% endblock content %}

faq/templates/faq/list-pertanyaan.html
{% extends 'base.html' %} 
{% load static %}
{% block meta %}
<link href="{% static 'cssfaq.css' %}" rel="stylesheet" type="text/css">
<style>
    .navbar{
        color: black;
        padding-right: 0%;
    }
    .navbar a{
        text-decoration: none;
        color: black;
        word-wrap: break-word;
        padding-left: 0%;
        padding-right: 0%;
    }
    .navbar div.collapse.navbar-collapse#navbarNavAltMarkup div.navbar-nav.ml-auto{
        padding-right: 0%;
    }
    footer{
        color: black;
        font-family: 'Poppins', sans-serif;
    }
</style>
{% endblock meta %}

{% block content %}
    <body>
        <div class="title">
            <p class="p-title">Frequently Asked Questions</p>
        </div>
        <div style="margin-top: 80px;">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">List Pertanyaan</th>
                    <th scope="col">Jawab?</th>
                </tr>
                </thead>
                <tbody>
                    {% for pertanyaan in pertanyaans %}
                        <tr>
                            <td class="p-td">{{pertanyaan.pertanyaan}}</td>
                            <td>
                                <a href="{% url 'faq:jawab' pertanyaan.id %}" class="btn" style="background-color: #FFE66D;">Jawab</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row mb-3 justify-content-center">
            <div class="col text-center">
                <a href="{% url 'faq:faq' %}" class="btn" style="background-color: #FFE66D;">Kembali ke Halaman FAQ</a>
            </div>
        </div>
{% endblock content %}