berita/urls.py
from django.urls import path

from . import views

app_name = 'berita'

urlpatterns = [
    path('', views.pageBerita, name='pageBerita'),
    path('makepost/', views.makePost, name='makePost'),
    path("post/<str:title>",views.detailPost,name="detailPost"),
    path("deletePost/<str:title>",views.deletePost,name="deletePost")

]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact'),
]

covid_starterpack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('covid_kit/', include('covid_kit.urls', namespace='covid_kit')),
    path('daftar-rs/', include(('list_rs.urls', 'list_rs'), namespace='list_rs')),
    path('daftarkasus/', include('list_kasus.urls',namespace ='listkasus')),
    path('berita/', include('berita.urls')),
    path('contact/', include('contact.urls')),
    path('faq/', include('faq.urls', namespace='faq')),
]

faq/urls.py
from django.urls import path, include

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq, name='faq'),
    path('list-pertanyaan/', views.list_pertanyaan, name='list-pertanyaan'),
    path('jawab/P<int:id_pertanyaan>/', views.jawab, name='jawab'),
    path('list-FAQ/', views.list_faq, name='list-faq'),
    path('detail/P<int:id_pertanyaan>/', views.detail, name='detail'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

list_rs/urls.py
from django.urls import path

from . import views

app_name = 'list_rs'

urlpatterns = [
    path('', views.savers, name='savers'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('hapus/<str:id>', views.hapus, name='hapus'),
    path('ubah/<str:id>', views.ubah, name='ubah'),
    path('tes-covid/', views.tescovid, name='tescovid'),
    path('tes-covid/tiket', views.savependaftar),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COVID-Starterpack</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block meta %} {% endblock meta %}
</head>
<body style="background-color: #1A535C;">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #FF6B6B;">
        
        <a class="navbar-brand" href="{% url 'homepage:homepage' %}">COVID-Starterpack</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'berita:pageBerita' %}" style="font-family: 'Poppins', sans-serif">Berita</a>
            <a class="nav-item nav-link" href="{% url 'listkasus:list_kasus' %}" style="font-family: 'Poppins', sans-serif">Daftar Kasus</a>
            <a class="nav-item nav-link" href="{% url 'covid_kit:covid_kit' %}" style="font-family: 'Poppins', sans-serif">COVID Kit</a>
            <a class="nav-item nav-link" href="{% url 'list_rs:savers' %}" style="font-family: 'Poppins', sans-serif">Rumah Sakit</a>
            <a class="nav-item nav-link" href="{% url 'faq:faq' %}" style="font-family: 'Poppins', sans-serif">FAQ</a>
            <a class="nav-item nav-link" href="{% url 'contact:contact' %}" style="font-family: 'Poppins', sans-serif">Contact</a>
        </div>
        </div>
    </nav>
    <div style="margin-top:70px; min-height: 515px;">
        {% block content %} {% endblock content %}
    </div>
    
    <footer style="background-color: #FF6B6B; padding: 5px;" class="text-center d-block w-100 position-absolute">
        ©2020 Maung, All rights reserved.
    </footer>

</body>
</html>