covid_kit/urls.py
from django.urls import path, include
from .views import barang, daftar_barang, daftar_pesanan, berhasil
app_name = 'covid_kit'
urlpatterns = [
    path('',barang, name="covid_kit"),
    path('daftar/',daftar_barang, name='daftar'),
    path('pesan/',daftar_pesanan, name='pesan'),
    path('berhasil/',berhasil, name='berhasil')
]

covid_starterpack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('covid_kit/', include('covid_kit.urls', namespace='covid_kit')),
    path('daftar-rs/', include(('list_rs.urls', 'list_rs'), namespace='list_rs')),
    path('daftarkasus/', include('list_kasus.urls',namespace ='listkasus')),
    path('berita/', include('berita.urls')),
    path('contact/', include('contact.urls')),
    path('faq/', include('faq.urls', namespace='faq')),
]

faq/urls.py
from django.urls import path, include

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq, name='faq'),
    path('list-pertanyaan/', views.list_pertanyaan, name='list-pertanyaan'),
    path('jawab/P<int:id_pertanyaan>/', views.jawab, name='jawab'),
    path('list-FAQ/', views.list_faq, name='list-faq'),
    path('detail/P<int:id_pertanyaan>/', views.detail, name='detail'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

list_kasus/urls.py
from django.urls import path
from . import views
app_name = 'list_kasus'

urlpatterns = [

    path('',views.list_kasus,name = 'list_kasus'),
    path('kasus_detail/<int:pk>/',views.kasus_detail, name = 'kasusdetail'),
    path('tambahkasus/', views.tambah_kasus, name='tambahkasus')
]

list_rs/urls.py
from django.urls import path

from . import views

app_name = 'list_rs'

urlpatterns = [
    path('', views.savers, name='savers'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('hapus/<str:id>', views.hapus, name='hapus'),
    path('ubah/<str:id>', views.ubah, name='ubah'),
    path('tes-covid/', views.tescovid, name='tescovid'),
    path('tes-covid/tiket', views.savependaftar),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from berita.models import Berita
from list_rs.models import RumahSakit
# Create your views here.
def homepage(request):
    context = {
        "listBerita" : Berita.objects.all().order_by("title"),
        "rs" : RumahSakit.objects.all().count()
    }
    return render(request, 'homepage.html', context)

homepage/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<link rel="stylesheet" href="{% static 'css/styleH.css' %}">
{% endblock meta %}
{% block content %}
    <div class="d-flex flex-column">

        <!-- Title Web -->
        <div class="d-flex flex-column flex-sm-row align-content-xl-center p-5 bg-secondary">
            <div class="mx-auto d-flex flex-column text-center w-sm-50-100">
                <h3>
                    Penjelasan COVID
                </h3> 
                <br>
                COVID-19 adalah penyakit yang disebabkan oleh virus severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). 
                COVID-19 dapat menyebabkan gangguan sistem pernapasan, mulai dari gejala yang ringan seperti flu, hingga infeksi paru-paru, 
                seperti pneumonia.
            </div>
            <div class="mx-auto d-flex align-self-center pt-5 pt-sm-0">
                <img src="{% static 'photos/corona.jpg' %}" alt="corona " width="150px" height="100px">
            </div>
        </div>

        <!-- Berita -->
        <div class="d-flex flex-column text-center align-content-xl-center bg-primary p-5">
            <h3>
                Berita Mengenai COVID
            </h3>
            <div class="d-flex flex-column flex-md-row">
                {% for berita in listBerita|slice:":2" %}
                <div class="text-center w-md-50-100 mx-auto mx-md-0 py-5">
                    <div class="bg-secondary w-75 mx-auto px-3">
                        <div class="font-weight-bold pt-3">
                            <a href="{{berita.get_absolute_url}}">
                                {{berita.title}}
                            </a>
                        </div>
                        <img class="mt-3" src={{berita.image_url}} alt="img" width="150px" height="100px">
                        <div style="width: 100%;" class="text-left p-3 mx-auto">
                            {{ berita.content|linebreaks|truncatechars:100 }}
                            <a href="{{berita.get_absolute_url}}" style="color: blue;">read more</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Total Kasus -->
        <div class="d-flex flex-column flex-sm-row align-content-xl-center">
            <div class="w-sm-50-100 text-center border-right-bottom align-content-center d-flex flex-column mx-auto bg-secondary p-5">
                
                    <h5>
                        Total Kasus di Indonesia
                    </h5>
                    <p  style="font-size: 40px;">
                        463007
                    </p>
                    <a href="{% url 'listkasus:list_kasus' %}" style="width: fit-content;" class="mx-auto">
                        <button style="font-size: 13px;" class="btn bg-yellow">
                            Cek Kasus di Daerahmu
                        </button>
                    </a>
                </span>
                
            </div>
            <div class="w-sm-50-100 text-center border-left-top align-content-center d-flex flex-column mx-auto bg-secondary p-5">
                <h5>
                    Total Rumah Sakit di Indonesia
                </p>
                <p style="font-size: 40px;">
                    {{rs}}
                </h5>
                <a href="{% url 'list_rs:savers' %}" style="width: fit-content;" class="mx-auto">
                    <button style="font-size: 13px;" class="btn bg-yellow">
                        Cek RS di Daerahmu
                    </button>
                </a>
            </div>
        </div>

        <!-- Gejala -->
        <div class="d-flex flex-column align-content-xl-center bg-primary p-5">
            <div class="pl-sm-5 pl-0 text-sm-left text-center">
                <h3>
                    Gejala
                </h3>
                <br>
                <p>
                    <ul class="list-unstyled text-left">
                        <li>
                            - Demam
                        </li>
                        <li>
                            - Batuk
                        </li>
                        <li>
                            - Sesak
                        </li>
                    </ul>
                </p>
            </div>
            
        </div>

        <!-- Penanganan -->
        <div class="d-flex flex-column bg-secondary p-5">
            <div class="pr-sm-5 pr-0 text-center text-sm-right">
                <h3>
                    Langkah yang harus dilakukan
                </h3>
                <br>
                <p>
                    <ul class="text-right list-unstyled">
                        <li>
                            Isolasi -
                        </li>
                        <li>
                            Jangan bertemu -
                        </li>
                        <li>
                            Rumah sakit -
                        </li>
                    </ul>
                </p>
            </div>
            
        </div>

        <!-- Harus dilakukan dan jangan dilakukan-->
        <div class="d-flex flex-column flex-sm-row align-content-xl-center bg-primary py-5 px-5">
            <div class="d-flex w-sm-50-100 border-right-bottom justify-content-center text-right mx-auto flex-column pr-0 pr-sm-5 pt-sm-0">
                <h3 class="text-center">Harus dilakukan</h3>
                <br>
                <div class="text-sm-right text-left">
                    Mencuci tangan
                    <br>
                    Memakai masker saat bepergian
                    <br>
                    Menutup mulut saat bersin maupun batuk
                </div>
            </div>
            <div class="d-flex w-sm-50-100 border-left-bottom justify-content-center mx-auto flex-column pl-0 pl-sm-5 pt-5 pt-sm-0"> 
                <h3 class="text-center pt-sm-0 pt-5">Jangan dilakukan</h3>
                <br>
                <div class="text-left">
                    Menyentuh wajah dengan tangan yang kotor
                    <br>
                    Bepergian ke tempat umum saat tidak penting
                    <br>
                    Percaya berita hoaks
                </div>
            </div>
        </div>

        <!-- COVID Kit -->
        <div class="d-flex flex-column align-content-xl-center bg-secondary p-5">
            <h3 class="align-self-center">COVID Kit</h3>
            <div class="d-flex flex-column flex-sm-row">
                <div class="d-flex align-self-center">
                    <p class="mx-auto w-sm-50-100 text-center">Cari barang-barang yang kamu butuhkan di masa pandemi seperti ini.</p>
                </div>
                
                <div class="d-flex w-50 align-self-center flex-column pt-5 pt-sm-0">
                    <img src="{% static 'photos/shopping-cart.png' %}" alt="pc" width="100px" height="100px" class="mx-auto">
                    <a href="{% url 'covid_kit:covid_kit' %}" style="width: fit-content;" class="mx-auto">
                        <button style="font-size: 13px;" class="btn bg-yellow">
                            Cari Barang
                        </button>
                    </a>
                </div>

            </div>
        </div>

    </div>
{% endblock content %}